window.PRODUCTIONS = [
  {
    id: "ekspres-donikad",
    title: "Ekspres donikąd",
    type: "Serial",
    director: "Ewlka17",
    directorSlug: "ewlka17",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Produkcja autorstwa Ewlka17.",
    cover: "https://placehold.co/600x900/392a4a/ffffff?text=Ekspres%20donik%C4%85d",
    episodes: Array.from({ length: 20 }, (_, i) => `Odcinek ${i + 1}`),
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-15"
  },
  {
    id: "pragnienie",
    title: "Pragnienie",
    type: "Serial",
    director: "Ewlka17",
    directorSlug: "ewlka17",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Produkcja autorstwa Ewlka17.",
    cover: "https://placehold.co/600x900/4a2735/ffffff?text=Pragnienie",
    episodes: Array.from({ length: 26 }, (_, i) => `Odcinek ${i + 1}`),
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-14"
  },
  {
    id: "zwykla-kasia",
    title: "Zwykła Kasia",
    type: "Serial",
    director: "Ewlka17",
    directorSlug: "ewlka17",
    genres: ["Inne"],
    status: "W trakcie",
    description: "Produkcja autorstwa Ewlka17.",
    cover: "https://placehold.co/600x900/334a40/ffffff?text=Zwyk%C5%82a%20Kasia",
    episodes: ["Odcinek 1", "Odcinek 2"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-13"
  },
  {
    id: "sposob-na-wampira",
    title: "Sposób na wampira",
    type: "Film",
    director: "Ewlka17",
    directorSlug: "ewlka17",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa Ewlka17.",
    cover: "https://placehold.co/600x900/3b2445/ffffff?text=Spos%C3%B3b%20na%20wampira",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-12"
  },
  {
    id: "foxy-i-kitty-ratuja-halloween",
    title: "Foxy i Kitty ratują Halloween",
    type: "Film",
    director: "Ewlka17",
    directorSlug: "ewlka17",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa Ewlka17.",
    cover: "https://placehold.co/600x900/5b3424/ffffff?text=Foxy%20i%20Kitty",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-11"
  },
  {
    id: "dokad-noca-tupta-jez",
    title: "Dokąd nocą tupta jeż?",
    type: "Film",
    director: "Ewlka17",
    directorSlug: "ewlka17",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa Ewlka17.",
    cover: "https://placehold.co/600x900/354531/ffffff?text=Dok%C4%85d%20noc%C4%85%20tupta%20je%C5%BC",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-10"
  },
  {
    id: "przygody-pajaka-przemka",
    title: "Przygody Pająka Przemka",
    type: "Serial",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Czteroczęściowa produkcja autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/2c3548/ffffff?text=Przygody%20Paj%C4%85ka%20Przemka",
    episodes: ["Część 1", "Część 2", "Część 3", "Część 4"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-09"
  },
  {
    id: "chory-pioter",
    title: "Chory Pioter",
    type: "Serial",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Czteroczęściowa produkcja autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/46342e/ffffff?text=Chory%20Pioter",
    episodes: ["Kamień Nerkowy", "Komórka Tajemnic", "Więzień Azkabanosa", "Czara Wody"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-08"
  },
  {
    id: "gang-przytulakow",
    title: "Gang Przytulaków",
    type: "Serial",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "W trakcie",
    description: "Siedmioczęściowa produkcja autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/49364d/ffffff?text=Gang%20Przytulak%C3%B3w",
    episodes: Array.from({ length: 7 }, (_, i) => `Część ${i + 1}`),
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-07"
  },
  {
    id: "co-robimy-w-ukryciu",
    title: "Co robimy w ukryciu?",
    type: "Film",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/283445/ffffff?text=Co%20robimy%20w%20ukryciu",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-06"
  },
  {
    id: "dyniowy-rycerz",
    title: "Dyniowy Rycerz",
    type: "Film",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/643815/ffffff?text=Dyniowy%20Rycerz",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-05"
  },
  {
    id: "koszmarna-chata",
    title: "Koszmarna Chata",
    type: "Film",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/372d35/ffffff?text=Koszmarna%20Chata",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-04"
  },
  {
    id: "swiete-halloween",
    title: "Święte Halloween",
    type: "Film",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/51331f/ffffff?text=%C5%9Awi%C4%99te%20Halloween",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-03"
  },
  {
    id: "swieto-jul",
    title: "Święto Jul",
    type: "Film",
    director: "MrokGalant",
    directorSlug: "mrokgalant",
    genres: ["Inne"],
    status: "Zakończone",
    description: "Film autorstwa MrokGalant.",
    cover: "https://placehold.co/600x900/244238/ffffff?text=%C5%9Awi%C4%99to%20Jul",
    episodes: ["Film"],
    rating: 10.0,
    ratingsCount: 1,
    watchedCount: 0,
    related: [],
    added: "2026-07-02"
  }
];

window.REVIEWS = {};
